// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"

	"ownhub/internal/biz"
	"ownhub/internal/conf"
	"ownhub/internal/data"
	"ownhub/internal/server"
	"ownhub/internal/service"
)

func wireApp(bc *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(bc.Data, logger)
	if err != nil {
		return nil, nil, err
	}
	hubRepo := data.NewHubRepo(dataData)
	shortRepo := data.NewShortRepo(dataData)
	hubUsecase := biz.NewHubUsecase(hubRepo, bc.App)
	shortUsecase := biz.NewShortUsecase(shortRepo, bc.App)
	toolUsecase := biz.NewToolUsecase(bc.App)
	portalService := service.NewPortalService(hubUsecase)
	shortService := service.NewShortService(shortUsecase)
	toolService := service.NewToolService(toolUsecase)
	httpServer := server.NewHTTPServer(bc.Server, shortService, toolService, portalService, bc.App, logger)
	grpcServer := server.NewGRPCServer(bc.Server, shortService, toolService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
