// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/google/wire"
	"ownhub/internal/biz"
	"ownhub/internal/conf"
	"ownhub/internal/data"
	"ownhub/internal/server"
	"ownhub/internal/service"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

// 👇 入口
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	confServer := newServer(bootstrap)
	confData := newData(bootstrap)
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	shortRepo := data.NewShortRepo(dataData)
	app := newAppConf(bootstrap)
	shortUsecase := biz.NewShortUsecase(shortRepo, app)
	shortService := service.NewShortService(shortUsecase)
	toolUsecase := biz.NewToolUsecase(app)
	toolService := service.NewToolService(toolUsecase)
	hubRepo := data.NewHubRepo(dataData)
	hubUsecase := biz.NewHubUsecase(hubRepo, app)
	portalService := service.NewPortalService(hubUsecase)
	httpServer := server.NewHTTPServer(confServer, shortService, toolService, portalService, app, logger)
	grpcServer := server.NewGRPCServer(confServer, shortService, toolService, logger)
	kratosApp := newApp(logger, httpServer, grpcServer)
	return kratosApp, func() {
		cleanup()
	}, nil
}

// wire.go:

// 👇 把 Bootstrap 拆成各个子配置
func newServer(c *conf.Bootstrap) *conf.Server {
	return c.Server
}

func newData(c *conf.Bootstrap) *conf.Data {
	return c.Data
}

func newAppConf(c *conf.Bootstrap) *conf.App {
	return c.App
}

// 👇 组装 Provider
var ProviderSet = wire.NewSet(server.ProviderSet, data.ProviderSet, biz.ProviderSet, service.ProviderSet, newServer,
	newData,
	newAppConf,

	newApp,
)
