// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: ownhub/v1/short.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationShortServiceCreateShort = "/ownhub.v1.ShortService/CreateShort"
const OperationShortServiceGetShort = "/ownhub.v1.ShortService/GetShort"
const OperationShortServiceRedirect = "/ownhub.v1.ShortService/Redirect"

type ShortServiceHTTPServer interface {
	CreateShort(context.Context, *CreateShortReq) (*CreateShortReply, error)
	GetShort(context.Context, *GetShortReq) (*GetShortReply, error)
	Redirect(context.Context, *RedirectReq) (*RedirectReply, error)
}

func RegisterShortServiceHTTPServer(s *http.Server, srv ShortServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/short-links", _ShortService_CreateShort0_HTTP_Handler(srv))
	r.GET("/api/v1/short-links/{code}", _ShortService_Redirect0_HTTP_Handler(srv))
	r.GET("/api/v1/short-links/{code}/detail", _ShortService_GetShort0_HTTP_Handler(srv))
}

func _ShortService_CreateShort0_HTTP_Handler(srv ShortServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateShortReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShortServiceCreateShort)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateShort(ctx, req.(*CreateShortReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateShortReply)
		return ctx.Result(200, reply)
	}
}

func _ShortService_Redirect0_HTTP_Handler(srv ShortServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RedirectReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShortServiceRedirect)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Redirect(ctx, req.(*RedirectReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RedirectReply)
		return ctx.Result(200, reply)
	}
}

func _ShortService_GetShort0_HTTP_Handler(srv ShortServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetShortReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShortServiceGetShort)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetShort(ctx, req.(*GetShortReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetShortReply)
		return ctx.Result(200, reply)
	}
}

type ShortServiceHTTPClient interface {
	CreateShort(ctx context.Context, req *CreateShortReq, opts ...http.CallOption) (rsp *CreateShortReply, err error)
	GetShort(ctx context.Context, req *GetShortReq, opts ...http.CallOption) (rsp *GetShortReply, err error)
	Redirect(ctx context.Context, req *RedirectReq, opts ...http.CallOption) (rsp *RedirectReply, err error)
}

type ShortServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewShortServiceHTTPClient(client *http.Client) ShortServiceHTTPClient {
	return &ShortServiceHTTPClientImpl{client}
}

func (c *ShortServiceHTTPClientImpl) CreateShort(ctx context.Context, in *CreateShortReq, opts ...http.CallOption) (*CreateShortReply, error) {
	var out CreateShortReply
	pattern := "/api/v1/short-links"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationShortServiceCreateShort))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShortServiceHTTPClientImpl) GetShort(ctx context.Context, in *GetShortReq, opts ...http.CallOption) (*GetShortReply, error) {
	var out GetShortReply
	pattern := "/api/v1/short-links/{code}/detail"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShortServiceGetShort))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShortServiceHTTPClientImpl) Redirect(ctx context.Context, in *RedirectReq, opts ...http.CallOption) (*RedirectReply, error) {
	var out RedirectReply
	pattern := "/api/v1/short-links/{code}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShortServiceRedirect))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
