// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ownhub/v1/short.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShortReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortReq) Reset() {
	*x = CreateShortReq{}
	mi := &file_ownhub_v1_short_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortReq) ProtoMessage() {}

func (x *CreateShortReq) ProtoReflect() protoreflect.Message {
	mi := &file_ownhub_v1_short_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortReq.ProtoReflect.Descriptor instead.
func (*CreateShortReq) Descriptor() ([]byte, []int) {
	return file_ownhub_v1_short_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateShortReq) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateShortReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateShortReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortReply) Reset() {
	*x = CreateShortReply{}
	mi := &file_ownhub_v1_short_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortReply) ProtoMessage() {}

func (x *CreateShortReply) ProtoReflect() protoreflect.Message {
	mi := &file_ownhub_v1_short_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortReply.ProtoReflect.Descriptor instead.
func (*CreateShortReply) Descriptor() ([]byte, []int) {
	return file_ownhub_v1_short_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateShortReply) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type RedirectReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectReq) Reset() {
	*x = RedirectReq{}
	mi := &file_ownhub_v1_short_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectReq) ProtoMessage() {}

func (x *RedirectReq) ProtoReflect() protoreflect.Message {
	mi := &file_ownhub_v1_short_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectReq.ProtoReflect.Descriptor instead.
func (*RedirectReq) Descriptor() ([]byte, []int) {
	return file_ownhub_v1_short_proto_rawDescGZIP(), []int{2}
}

func (x *RedirectReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type RedirectReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectReply) Reset() {
	*x = RedirectReply{}
	mi := &file_ownhub_v1_short_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectReply) ProtoMessage() {}

func (x *RedirectReply) ProtoReflect() protoreflect.Message {
	mi := &file_ownhub_v1_short_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectReply.ProtoReflect.Descriptor instead.
func (*RedirectReply) Descriptor() ([]byte, []int) {
	return file_ownhub_v1_short_proto_rawDescGZIP(), []int{3}
}

func (x *RedirectReply) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetShortReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortReq) Reset() {
	*x = GetShortReq{}
	mi := &file_ownhub_v1_short_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortReq) ProtoMessage() {}

func (x *GetShortReq) ProtoReflect() protoreflect.Message {
	mi := &file_ownhub_v1_short_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortReq.ProtoReflect.Descriptor instead.
func (*GetShortReq) Descriptor() ([]byte, []int) {
	return file_ownhub_v1_short_proto_rawDescGZIP(), []int{4}
}

func (x *GetShortReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetShortReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,3,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,5,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortReply) Reset() {
	*x = GetShortReply{}
	mi := &file_ownhub_v1_short_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortReply) ProtoMessage() {}

func (x *GetShortReply) ProtoReflect() protoreflect.Message {
	mi := &file_ownhub_v1_short_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortReply.ProtoReflect.Descriptor instead.
func (*GetShortReply) Descriptor() ([]byte, []int) {
	return file_ownhub_v1_short_proto_rawDescGZIP(), []int{5}
}

func (x *GetShortReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetShortReply) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetShortReply) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *GetShortReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetShortReply) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

var File_ownhub_v1_short_proto protoreflect.FileDescriptor

const file_ownhub_v1_short_proto_rawDesc = "" +
	"\n" +
	"\x15ownhub/v1/short.proto\x12\townhub.v1\x1a\x1cgoogle/api/annotations.proto\"X\n" +
	"\x0eCreateShortReq\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"C\n" +
	"\x10CreateShortReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"!\n" +
	"\vRedirectReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"!\n" +
	"\rRedirectReply\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"!\n" +
	"\vGetShortReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x9c\x01\n" +
	"\rGetShortReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1b\n" +
	"\tshort_url\x18\x03 \x01(\tR\bshortUrl\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12&\n" +
	"\x0fcreated_at_unix\x18\x05 \x01(\x03R\rcreatedAtUnix2\xc0\x02\n" +
	"\fShortService\x12e\n" +
	"\vCreateShort\x12\x19.ownhub.v1.CreateShortReq\x1a\x1b.ownhub.v1.CreateShortReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/short-links\x12`\n" +
	"\bRedirect\x12\x16.ownhub.v1.RedirectReq\x1a\x18.ownhub.v1.RedirectReply\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/short-links/{code}\x12g\n" +
	"\bGetShort\x12\x16.ownhub.v1.GetShortReq\x1a\x18.ownhub.v1.GetShortReply\")\x82\xd3\xe4\x93\x02#\x12!/api/v1/short-links/{code}/detailB\x19Z\x17ownhub/api/ownhub/v1;v1b\x06proto3"

var (
	file_ownhub_v1_short_proto_rawDescOnce sync.Once
	file_ownhub_v1_short_proto_rawDescData []byte
)

func file_ownhub_v1_short_proto_rawDescGZIP() []byte {
	file_ownhub_v1_short_proto_rawDescOnce.Do(func() {
		file_ownhub_v1_short_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ownhub_v1_short_proto_rawDesc), len(file_ownhub_v1_short_proto_rawDesc)))
	})
	return file_ownhub_v1_short_proto_rawDescData
}

var file_ownhub_v1_short_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ownhub_v1_short_proto_goTypes = []any{
	(*CreateShortReq)(nil),   // 0: ownhub.v1.CreateShortReq
	(*CreateShortReply)(nil), // 1: ownhub.v1.CreateShortReply
	(*RedirectReq)(nil),      // 2: ownhub.v1.RedirectReq
	(*RedirectReply)(nil),    // 3: ownhub.v1.RedirectReply
	(*GetShortReq)(nil),      // 4: ownhub.v1.GetShortReq
	(*GetShortReply)(nil),    // 5: ownhub.v1.GetShortReply
}
var file_ownhub_v1_short_proto_depIdxs = []int32{
	0, // 0: ownhub.v1.ShortService.CreateShort:input_type -> ownhub.v1.CreateShortReq
	2, // 1: ownhub.v1.ShortService.Redirect:input_type -> ownhub.v1.RedirectReq
	4, // 2: ownhub.v1.ShortService.GetShort:input_type -> ownhub.v1.GetShortReq
	1, // 3: ownhub.v1.ShortService.CreateShort:output_type -> ownhub.v1.CreateShortReply
	3, // 4: ownhub.v1.ShortService.Redirect:output_type -> ownhub.v1.RedirectReply
	5, // 5: ownhub.v1.ShortService.GetShort:output_type -> ownhub.v1.GetShortReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ownhub_v1_short_proto_init() }
func file_ownhub_v1_short_proto_init() {
	if File_ownhub_v1_short_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ownhub_v1_short_proto_rawDesc), len(file_ownhub_v1_short_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ownhub_v1_short_proto_goTypes,
		DependencyIndexes: file_ownhub_v1_short_proto_depIdxs,
		MessageInfos:      file_ownhub_v1_short_proto_msgTypes,
	}.Build()
	File_ownhub_v1_short_proto = out.File
	file_ownhub_v1_short_proto_goTypes = nil
	file_ownhub_v1_short_proto_depIdxs = nil
}
