// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: ownhub/v1/short.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShortService_CreateShort_FullMethodName = "/ownhub.v1.ShortService/CreateShort"
	ShortService_Redirect_FullMethodName    = "/ownhub.v1.ShortService/Redirect"
	ShortService_GetShort_FullMethodName    = "/ownhub.v1.ShortService/GetShort"
)

// ShortServiceClient is the client API for ShortService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShortServiceClient interface {
	CreateShort(ctx context.Context, in *CreateShortReq, opts ...grpc.CallOption) (*CreateShortReply, error)
	Redirect(ctx context.Context, in *RedirectReq, opts ...grpc.CallOption) (*RedirectReply, error)
	GetShort(ctx context.Context, in *GetShortReq, opts ...grpc.CallOption) (*GetShortReply, error)
}

type shortServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShortServiceClient(cc grpc.ClientConnInterface) ShortServiceClient {
	return &shortServiceClient{cc}
}

func (c *shortServiceClient) CreateShort(ctx context.Context, in *CreateShortReq, opts ...grpc.CallOption) (*CreateShortReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateShortReply)
	err := c.cc.Invoke(ctx, ShortService_CreateShort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortServiceClient) Redirect(ctx context.Context, in *RedirectReq, opts ...grpc.CallOption) (*RedirectReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedirectReply)
	err := c.cc.Invoke(ctx, ShortService_Redirect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortServiceClient) GetShort(ctx context.Context, in *GetShortReq, opts ...grpc.CallOption) (*GetShortReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShortReply)
	err := c.cc.Invoke(ctx, ShortService_GetShort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortServiceServer is the server API for ShortService service.
// All implementations must embed UnimplementedShortServiceServer
// for forward compatibility.
type ShortServiceServer interface {
	CreateShort(context.Context, *CreateShortReq) (*CreateShortReply, error)
	Redirect(context.Context, *RedirectReq) (*RedirectReply, error)
	GetShort(context.Context, *GetShortReq) (*GetShortReply, error)
	mustEmbedUnimplementedShortServiceServer()
}

// UnimplementedShortServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShortServiceServer struct{}

func (UnimplementedShortServiceServer) CreateShort(context.Context, *CreateShortReq) (*CreateShortReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShort not implemented")
}
func (UnimplementedShortServiceServer) Redirect(context.Context, *RedirectReq) (*RedirectReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Redirect not implemented")
}
func (UnimplementedShortServiceServer) GetShort(context.Context, *GetShortReq) (*GetShortReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShort not implemented")
}
func (UnimplementedShortServiceServer) mustEmbedUnimplementedShortServiceServer() {}
func (UnimplementedShortServiceServer) testEmbeddedByValue()                      {}

// UnsafeShortServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShortServiceServer will
// result in compilation errors.
type UnsafeShortServiceServer interface {
	mustEmbedUnimplementedShortServiceServer()
}

func RegisterShortServiceServer(s grpc.ServiceRegistrar, srv ShortServiceServer) {
	// If the following call panics, it indicates UnimplementedShortServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShortService_ServiceDesc, srv)
}

func _ShortService_CreateShort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShortReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortServiceServer).CreateShort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShortService_CreateShort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortServiceServer).CreateShort(ctx, req.(*CreateShortReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortService_Redirect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedirectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortServiceServer).Redirect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShortService_Redirect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortServiceServer).Redirect(ctx, req.(*RedirectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortService_GetShort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShortReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortServiceServer).GetShort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShortService_GetShort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortServiceServer).GetShort(ctx, req.(*GetShortReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ShortService_ServiceDesc is the grpc.ServiceDesc for ShortService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShortService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ownhub.v1.ShortService",
	HandlerType: (*ShortServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateShort",
			Handler:    _ShortService_CreateShort_Handler,
		},
		{
			MethodName: "Redirect",
			Handler:    _ShortService_Redirect_Handler,
		},
		{
			MethodName: "GetShort",
			Handler:    _ShortService_GetShort_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ownhub/v1/short.proto",
}
