// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ownhub/v1/tool.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_ownhub_v1_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_ownhub_v1_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_ownhub_v1_tool_proto_rawDescGZIP(), []int{0}
}

type PingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Now           string                 `protobuf:"bytes,3,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	mi := &file_ownhub_v1_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_ownhub_v1_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_ownhub_v1_tool_proto_rawDescGZIP(), []int{1}
}

func (x *PingReply) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *PingReply) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingReply) GetNow() string {
	if x != nil {
		return x.Now
	}
	return ""
}

type GetTimestampReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timezone      string                 `protobuf:"bytes,1,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimestampReq) Reset() {
	*x = GetTimestampReq{}
	mi := &file_ownhub_v1_tool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimestampReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimestampReq) ProtoMessage() {}

func (x *GetTimestampReq) ProtoReflect() protoreflect.Message {
	mi := &file_ownhub_v1_tool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimestampReq.ProtoReflect.Descriptor instead.
func (*GetTimestampReq) Descriptor() ([]byte, []int) {
	return file_ownhub_v1_tool_proto_rawDescGZIP(), []int{2}
}

func (x *GetTimestampReq) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type GetTimestampReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unix          int64                  `protobuf:"varint,1,opt,name=unix,proto3" json:"unix,omitempty"`
	Rfc3339       string                 `protobuf:"bytes,2,opt,name=rfc3339,proto3" json:"rfc3339,omitempty"`
	Timezone      string                 `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimestampReply) Reset() {
	*x = GetTimestampReply{}
	mi := &file_ownhub_v1_tool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimestampReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimestampReply) ProtoMessage() {}

func (x *GetTimestampReply) ProtoReflect() protoreflect.Message {
	mi := &file_ownhub_v1_tool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimestampReply.ProtoReflect.Descriptor instead.
func (*GetTimestampReply) Descriptor() ([]byte, []int) {
	return file_ownhub_v1_tool_proto_rawDescGZIP(), []int{3}
}

func (x *GetTimestampReply) GetUnix() int64 {
	if x != nil {
		return x.Unix
	}
	return 0
}

func (x *GetTimestampReply) GetRfc3339() string {
	if x != nil {
		return x.Rfc3339
	}
	return ""
}

func (x *GetTimestampReply) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type GenerateTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        int32                  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTokenReq) Reset() {
	*x = GenerateTokenReq{}
	mi := &file_ownhub_v1_tool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTokenReq) ProtoMessage() {}

func (x *GenerateTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_ownhub_v1_tool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTokenReq.ProtoReflect.Descriptor instead.
func (*GenerateTokenReq) Descriptor() ([]byte, []int) {
	return file_ownhub_v1_tool_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateTokenReq) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type GenerateTokenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Length        int32                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTokenReply) Reset() {
	*x = GenerateTokenReply{}
	mi := &file_ownhub_v1_tool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTokenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTokenReply) ProtoMessage() {}

func (x *GenerateTokenReply) ProtoReflect() protoreflect.Message {
	mi := &file_ownhub_v1_tool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTokenReply.ProtoReflect.Descriptor instead.
func (*GenerateTokenReply) Descriptor() ([]byte, []int) {
	return file_ownhub_v1_tool_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateTokenReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GenerateTokenReply) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type DigestTextReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigestTextReq) Reset() {
	*x = DigestTextReq{}
	mi := &file_ownhub_v1_tool_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestTextReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestTextReq) ProtoMessage() {}

func (x *DigestTextReq) ProtoReflect() protoreflect.Message {
	mi := &file_ownhub_v1_tool_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestTextReq.ProtoReflect.Descriptor instead.
func (*DigestTextReq) Descriptor() ([]byte, []int) {
	return file_ownhub_v1_tool_proto_rawDescGZIP(), []int{6}
}

func (x *DigestTextReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DigestTextReq) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

type DigestTextReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigestTextReply) Reset() {
	*x = DigestTextReply{}
	mi := &file_ownhub_v1_tool_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestTextReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestTextReply) ProtoMessage() {}

func (x *DigestTextReply) ProtoReflect() protoreflect.Message {
	mi := &file_ownhub_v1_tool_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestTextReply.ProtoReflect.Descriptor instead.
func (*DigestTextReply) Descriptor() ([]byte, []int) {
	return file_ownhub_v1_tool_proto_rawDescGZIP(), []int{7}
}

func (x *DigestTextReply) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *DigestTextReply) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

var File_ownhub_v1_tool_proto protoreflect.FileDescriptor

const file_ownhub_v1_tool_proto_rawDesc = "" +
	"\n" +
	"\x14ownhub/v1/tool.proto\x12\townhub.v1\x1a\x1cgoogle/api/annotations.proto\"\t\n" +
	"\aPingReq\"Q\n" +
	"\tPingReply\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x10\n" +
	"\x03now\x18\x03 \x01(\tR\x03now\"-\n" +
	"\x0fGetTimestampReq\x12\x1a\n" +
	"\btimezone\x18\x01 \x01(\tR\btimezone\"]\n" +
	"\x11GetTimestampReply\x12\x12\n" +
	"\x04unix\x18\x01 \x01(\x03R\x04unix\x12\x18\n" +
	"\arfc3339\x18\x02 \x01(\tR\arfc3339\x12\x1a\n" +
	"\btimezone\x18\x03 \x01(\tR\btimezone\"*\n" +
	"\x10GenerateTokenReq\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x05R\x06length\"B\n" +
	"\x12GenerateTokenReply\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length\"A\n" +
	"\rDigestTextReq\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\"G\n" +
	"\x0fDigestTextReply\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest2\x98\x03\n" +
	"\vToolService\x12L\n" +
	"\x04Ping\x12\x12.ownhub.v1.PingReq\x1a\x14.ownhub.v1.PingReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/tools/ping\x12i\n" +
	"\fGetTimestamp\x12\x1a.ownhub.v1.GetTimestampReq\x1a\x1c.ownhub.v1.GetTimestampReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/tools/timestamp\x12k\n" +
	"\rGenerateToken\x12\x1b.ownhub.v1.GenerateTokenReq\x1a\x1d.ownhub.v1.GenerateTokenReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/tools/token\x12c\n" +
	"\n" +
	"DigestText\x12\x18.ownhub.v1.DigestTextReq\x1a\x1a.ownhub.v1.DigestTextReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/tools/digestB\x19Z\x17ownhub/api/ownhub/v1;v1b\x06proto3"

var (
	file_ownhub_v1_tool_proto_rawDescOnce sync.Once
	file_ownhub_v1_tool_proto_rawDescData []byte
)

func file_ownhub_v1_tool_proto_rawDescGZIP() []byte {
	file_ownhub_v1_tool_proto_rawDescOnce.Do(func() {
		file_ownhub_v1_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ownhub_v1_tool_proto_rawDesc), len(file_ownhub_v1_tool_proto_rawDesc)))
	})
	return file_ownhub_v1_tool_proto_rawDescData
}

var file_ownhub_v1_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ownhub_v1_tool_proto_goTypes = []any{
	(*PingReq)(nil),            // 0: ownhub.v1.PingReq
	(*PingReply)(nil),          // 1: ownhub.v1.PingReply
	(*GetTimestampReq)(nil),    // 2: ownhub.v1.GetTimestampReq
	(*GetTimestampReply)(nil),  // 3: ownhub.v1.GetTimestampReply
	(*GenerateTokenReq)(nil),   // 4: ownhub.v1.GenerateTokenReq
	(*GenerateTokenReply)(nil), // 5: ownhub.v1.GenerateTokenReply
	(*DigestTextReq)(nil),      // 6: ownhub.v1.DigestTextReq
	(*DigestTextReply)(nil),    // 7: ownhub.v1.DigestTextReply
}
var file_ownhub_v1_tool_proto_depIdxs = []int32{
	0, // 0: ownhub.v1.ToolService.Ping:input_type -> ownhub.v1.PingReq
	2, // 1: ownhub.v1.ToolService.GetTimestamp:input_type -> ownhub.v1.GetTimestampReq
	4, // 2: ownhub.v1.ToolService.GenerateToken:input_type -> ownhub.v1.GenerateTokenReq
	6, // 3: ownhub.v1.ToolService.DigestText:input_type -> ownhub.v1.DigestTextReq
	1, // 4: ownhub.v1.ToolService.Ping:output_type -> ownhub.v1.PingReply
	3, // 5: ownhub.v1.ToolService.GetTimestamp:output_type -> ownhub.v1.GetTimestampReply
	5, // 6: ownhub.v1.ToolService.GenerateToken:output_type -> ownhub.v1.GenerateTokenReply
	7, // 7: ownhub.v1.ToolService.DigestText:output_type -> ownhub.v1.DigestTextReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ownhub_v1_tool_proto_init() }
func file_ownhub_v1_tool_proto_init() {
	if File_ownhub_v1_tool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ownhub_v1_tool_proto_rawDesc), len(file_ownhub_v1_tool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ownhub_v1_tool_proto_goTypes,
		DependencyIndexes: file_ownhub_v1_tool_proto_depIdxs,
		MessageInfos:      file_ownhub_v1_tool_proto_msgTypes,
	}.Build()
	File_ownhub_v1_tool_proto = out.File
	file_ownhub_v1_tool_proto_goTypes = nil
	file_ownhub_v1_tool_proto_depIdxs = nil
}
