// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: ownhub/v1/tool.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationToolServiceDigestText = "/ownhub.v1.ToolService/DigestText"
const OperationToolServiceGenerateToken = "/ownhub.v1.ToolService/GenerateToken"
const OperationToolServiceGetTimestamp = "/ownhub.v1.ToolService/GetTimestamp"
const OperationToolServicePing = "/ownhub.v1.ToolService/Ping"

type ToolServiceHTTPServer interface {
	DigestText(context.Context, *DigestTextReq) (*DigestTextReply, error)
	GenerateToken(context.Context, *GenerateTokenReq) (*GenerateTokenReply, error)
	GetTimestamp(context.Context, *GetTimestampReq) (*GetTimestampReply, error)
	Ping(context.Context, *PingReq) (*PingReply, error)
}

func RegisterToolServiceHTTPServer(s *http.Server, srv ToolServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/tools/ping", _ToolService_Ping0_HTTP_Handler(srv))
	r.GET("/api/v1/tools/timestamp", _ToolService_GetTimestamp0_HTTP_Handler(srv))
	r.POST("/api/v1/tools/token", _ToolService_GenerateToken0_HTTP_Handler(srv))
	r.POST("/api/v1/tools/digest", _ToolService_DigestText0_HTTP_Handler(srv))
}

func _ToolService_Ping0_HTTP_Handler(srv ToolServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PingReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationToolServicePing)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Ping(ctx, req.(*PingReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PingReply)
		return ctx.Result(200, reply)
	}
}

func _ToolService_GetTimestamp0_HTTP_Handler(srv ToolServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTimestampReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationToolServiceGetTimestamp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTimestamp(ctx, req.(*GetTimestampReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTimestampReply)
		return ctx.Result(200, reply)
	}
}

func _ToolService_GenerateToken0_HTTP_Handler(srv ToolServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GenerateTokenReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationToolServiceGenerateToken)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GenerateToken(ctx, req.(*GenerateTokenReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GenerateTokenReply)
		return ctx.Result(200, reply)
	}
}

func _ToolService_DigestText0_HTTP_Handler(srv ToolServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DigestTextReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationToolServiceDigestText)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DigestText(ctx, req.(*DigestTextReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DigestTextReply)
		return ctx.Result(200, reply)
	}
}

type ToolServiceHTTPClient interface {
	DigestText(ctx context.Context, req *DigestTextReq, opts ...http.CallOption) (rsp *DigestTextReply, err error)
	GenerateToken(ctx context.Context, req *GenerateTokenReq, opts ...http.CallOption) (rsp *GenerateTokenReply, err error)
	GetTimestamp(ctx context.Context, req *GetTimestampReq, opts ...http.CallOption) (rsp *GetTimestampReply, err error)
	Ping(ctx context.Context, req *PingReq, opts ...http.CallOption) (rsp *PingReply, err error)
}

type ToolServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewToolServiceHTTPClient(client *http.Client) ToolServiceHTTPClient {
	return &ToolServiceHTTPClientImpl{client}
}

func (c *ToolServiceHTTPClientImpl) DigestText(ctx context.Context, in *DigestTextReq, opts ...http.CallOption) (*DigestTextReply, error) {
	var out DigestTextReply
	pattern := "/api/v1/tools/digest"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationToolServiceDigestText))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ToolServiceHTTPClientImpl) GenerateToken(ctx context.Context, in *GenerateTokenReq, opts ...http.CallOption) (*GenerateTokenReply, error) {
	var out GenerateTokenReply
	pattern := "/api/v1/tools/token"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationToolServiceGenerateToken))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ToolServiceHTTPClientImpl) GetTimestamp(ctx context.Context, in *GetTimestampReq, opts ...http.CallOption) (*GetTimestampReply, error) {
	var out GetTimestampReply
	pattern := "/api/v1/tools/timestamp"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationToolServiceGetTimestamp))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ToolServiceHTTPClientImpl) Ping(ctx context.Context, in *PingReq, opts ...http.CallOption) (*PingReply, error) {
	var out PingReply
	pattern := "/api/v1/tools/ping"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationToolServicePing))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
