// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/ownhub/v1/tool.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ===== 现有消息定义 =====
type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_api_ownhub_v1_tool_proto_rawDescGZIP(), []int{0}
}

type PingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Now           string                 `protobuf:"bytes,3,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_api_ownhub_v1_tool_proto_rawDescGZIP(), []int{1}
}

func (x *PingReply) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *PingReply) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingReply) GetNow() string {
	if x != nil {
		return x.Now
	}
	return ""
}

type GetTimestampReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timezone      string                 `protobuf:"bytes,1,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimestampReq) Reset() {
	*x = GetTimestampReq{}
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimestampReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimestampReq) ProtoMessage() {}

func (x *GetTimestampReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimestampReq.ProtoReflect.Descriptor instead.
func (*GetTimestampReq) Descriptor() ([]byte, []int) {
	return file_api_ownhub_v1_tool_proto_rawDescGZIP(), []int{2}
}

func (x *GetTimestampReq) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type GetTimestampReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unix          int64                  `protobuf:"varint,1,opt,name=unix,proto3" json:"unix,omitempty"`
	Rfc3339       string                 `protobuf:"bytes,2,opt,name=rfc3339,proto3" json:"rfc3339,omitempty"`
	Timezone      string                 `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimestampReply) Reset() {
	*x = GetTimestampReply{}
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimestampReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimestampReply) ProtoMessage() {}

func (x *GetTimestampReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimestampReply.ProtoReflect.Descriptor instead.
func (*GetTimestampReply) Descriptor() ([]byte, []int) {
	return file_api_ownhub_v1_tool_proto_rawDescGZIP(), []int{3}
}

func (x *GetTimestampReply) GetUnix() int64 {
	if x != nil {
		return x.Unix
	}
	return 0
}

func (x *GetTimestampReply) GetRfc3339() string {
	if x != nil {
		return x.Rfc3339
	}
	return ""
}

func (x *GetTimestampReply) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type GenerateTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        int32                  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTokenReq) Reset() {
	*x = GenerateTokenReq{}
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTokenReq) ProtoMessage() {}

func (x *GenerateTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTokenReq.ProtoReflect.Descriptor instead.
func (*GenerateTokenReq) Descriptor() ([]byte, []int) {
	return file_api_ownhub_v1_tool_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateTokenReq) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type GenerateTokenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Length        int32                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTokenReply) Reset() {
	*x = GenerateTokenReply{}
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTokenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTokenReply) ProtoMessage() {}

func (x *GenerateTokenReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTokenReply.ProtoReflect.Descriptor instead.
func (*GenerateTokenReply) Descriptor() ([]byte, []int) {
	return file_api_ownhub_v1_tool_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateTokenReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GenerateTokenReply) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type DigestTextReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigestTextReq) Reset() {
	*x = DigestTextReq{}
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestTextReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestTextReq) ProtoMessage() {}

func (x *DigestTextReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestTextReq.ProtoReflect.Descriptor instead.
func (*DigestTextReq) Descriptor() ([]byte, []int) {
	return file_api_ownhub_v1_tool_proto_rawDescGZIP(), []int{6}
}

func (x *DigestTextReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DigestTextReq) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

type DigestTextReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigestTextReply) Reset() {
	*x = DigestTextReply{}
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestTextReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestTextReply) ProtoMessage() {}

func (x *DigestTextReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestTextReply.ProtoReflect.Descriptor instead.
func (*DigestTextReply) Descriptor() ([]byte, []int) {
	return file_api_ownhub_v1_tool_proto_rawDescGZIP(), []int{7}
}

func (x *DigestTextReply) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *DigestTextReply) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

// ===== 新增 AI 消息定义 =====
type AIChatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	History       []*ChatMessage         `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIChatReq) Reset() {
	*x = AIChatReq{}
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatReq) ProtoMessage() {}

func (x *AIChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatReq.ProtoReflect.Descriptor instead.
func (*AIChatReq) Descriptor() ([]byte, []int) {
	return file_api_ownhub_v1_tool_proto_rawDescGZIP(), []int{8}
}

func (x *AIChatReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AIChatReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AIChatReq) GetHistory() []*ChatMessage {
	if x != nil {
		return x.History
	}
	return nil
}

type AIChatReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	TokensUsed    int64                  `protobuf:"varint,3,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIChatReply) Reset() {
	*x = AIChatReply{}
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIChatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatReply) ProtoMessage() {}

func (x *AIChatReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatReply.ProtoReflect.Descriptor instead.
func (*AIChatReply) Descriptor() ([]byte, []int) {
	return file_api_ownhub_v1_tool_proto_rawDescGZIP(), []int{9}
}

func (x *AIChatReply) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *AIChatReply) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AIChatReply) GetTokensUsed() int64 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // user, assistant, system
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_api_ownhub_v1_tool_proto_rawDescGZIP(), []int{10}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AIProcessTextReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`                           // translate, summarize, polish, grammar
	TargetLang    string                 `protobuf:"bytes,3,opt,name=target_lang,json=targetLang,proto3" json:"target_lang,omitempty"` // 翻译目标语言
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIProcessTextReq) Reset() {
	*x = AIProcessTextReq{}
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIProcessTextReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIProcessTextReq) ProtoMessage() {}

func (x *AIProcessTextReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIProcessTextReq.ProtoReflect.Descriptor instead.
func (*AIProcessTextReq) Descriptor() ([]byte, []int) {
	return file_api_ownhub_v1_tool_proto_rawDescGZIP(), []int{11}
}

func (x *AIProcessTextReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AIProcessTextReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AIProcessTextReq) GetTargetLang() string {
	if x != nil {
		return x.TargetLang
	}
	return ""
}

type AIProcessTextReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Original      string                 `protobuf:"bytes,1,opt,name=original,proto3" json:"original,omitempty"`
	Processed     string                 `protobuf:"bytes,2,opt,name=processed,proto3" json:"processed,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIProcessTextReply) Reset() {
	*x = AIProcessTextReply{}
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIProcessTextReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIProcessTextReply) ProtoMessage() {}

func (x *AIProcessTextReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_ownhub_v1_tool_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIProcessTextReply.ProtoReflect.Descriptor instead.
func (*AIProcessTextReply) Descriptor() ([]byte, []int) {
	return file_api_ownhub_v1_tool_proto_rawDescGZIP(), []int{12}
}

func (x *AIProcessTextReply) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

func (x *AIProcessTextReply) GetProcessed() string {
	if x != nil {
		return x.Processed
	}
	return ""
}

func (x *AIProcessTextReply) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_api_ownhub_v1_tool_proto protoreflect.FileDescriptor

const file_api_ownhub_v1_tool_proto_rawDesc = "" +
	"\n" +
	"\x18api/ownhub/v1/tool.proto\x12\townhub.v1\x1a\x1cgoogle/api/annotations.proto\"\t\n" +
	"\aPingReq\"Q\n" +
	"\tPingReply\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x10\n" +
	"\x03now\x18\x03 \x01(\tR\x03now\"-\n" +
	"\x0fGetTimestampReq\x12\x1a\n" +
	"\btimezone\x18\x01 \x01(\tR\btimezone\"]\n" +
	"\x11GetTimestampReply\x12\x12\n" +
	"\x04unix\x18\x01 \x01(\x03R\x04unix\x12\x18\n" +
	"\arfc3339\x18\x02 \x01(\tR\arfc3339\x12\x1a\n" +
	"\btimezone\x18\x03 \x01(\tR\btimezone\"*\n" +
	"\x10GenerateTokenReq\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x05R\x06length\"B\n" +
	"\x12GenerateTokenReply\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length\"A\n" +
	"\rDigestTextReq\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\"G\n" +
	"\x0fDigestTextReply\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\"m\n" +
	"\tAIChatReq\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x120\n" +
	"\ahistory\x18\x03 \x03(\v2\x16.ownhub.v1.ChatMessageR\ahistory\"`\n" +
	"\vAIChatReply\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1f\n" +
	"\vtokens_used\x18\x03 \x01(\x03R\n" +
	"tokensUsed\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"_\n" +
	"\x10AIProcessTextReq\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1f\n" +
	"\vtarget_lang\x18\x03 \x01(\tR\n" +
	"targetLang\"f\n" +
	"\x12AIProcessTextReply\x12\x1a\n" +
	"\boriginal\x18\x01 \x01(\tR\boriginal\x12\x1c\n" +
	"\tprocessed\x18\x02 \x01(\tR\tprocessed\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action2\xe4\x04\n" +
	"\vToolService\x12L\n" +
	"\x04Ping\x12\x12.ownhub.v1.PingReq\x1a\x14.ownhub.v1.PingReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/tools/ping\x12i\n" +
	"\fGetTimestamp\x12\x1a.ownhub.v1.GetTimestampReq\x1a\x1c.ownhub.v1.GetTimestampReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/tools/timestamp\x12k\n" +
	"\rGenerateToken\x12\x1b.ownhub.v1.GenerateTokenReq\x1a\x1d.ownhub.v1.GenerateTokenReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/tools/token\x12c\n" +
	"\n" +
	"DigestText\x12\x18.ownhub.v1.DigestTextReq\x1a\x1a.ownhub.v1.DigestTextReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/tools/digest\x12X\n" +
	"\x06AIChat\x12\x14.ownhub.v1.AIChatReq\x1a\x16.ownhub.v1.AIChatReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/tools/ai/chat\x12p\n" +
	"\rAIProcessText\x12\x1b.ownhub.v1.AIProcessTextReq\x1a\x1d.ownhub.v1.AIProcessTextReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/tools/ai/processB\x19Z\x17ownhub/api/ownhub/v1;v1b\x06proto3"

var (
	file_api_ownhub_v1_tool_proto_rawDescOnce sync.Once
	file_api_ownhub_v1_tool_proto_rawDescData []byte
)

func file_api_ownhub_v1_tool_proto_rawDescGZIP() []byte {
	file_api_ownhub_v1_tool_proto_rawDescOnce.Do(func() {
		file_api_ownhub_v1_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ownhub_v1_tool_proto_rawDesc), len(file_api_ownhub_v1_tool_proto_rawDesc)))
	})
	return file_api_ownhub_v1_tool_proto_rawDescData
}

var file_api_ownhub_v1_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_ownhub_v1_tool_proto_goTypes = []any{
	(*PingReq)(nil),            // 0: ownhub.v1.PingReq
	(*PingReply)(nil),          // 1: ownhub.v1.PingReply
	(*GetTimestampReq)(nil),    // 2: ownhub.v1.GetTimestampReq
	(*GetTimestampReply)(nil),  // 3: ownhub.v1.GetTimestampReply
	(*GenerateTokenReq)(nil),   // 4: ownhub.v1.GenerateTokenReq
	(*GenerateTokenReply)(nil), // 5: ownhub.v1.GenerateTokenReply
	(*DigestTextReq)(nil),      // 6: ownhub.v1.DigestTextReq
	(*DigestTextReply)(nil),    // 7: ownhub.v1.DigestTextReply
	(*AIChatReq)(nil),          // 8: ownhub.v1.AIChatReq
	(*AIChatReply)(nil),        // 9: ownhub.v1.AIChatReply
	(*ChatMessage)(nil),        // 10: ownhub.v1.ChatMessage
	(*AIProcessTextReq)(nil),   // 11: ownhub.v1.AIProcessTextReq
	(*AIProcessTextReply)(nil), // 12: ownhub.v1.AIProcessTextReply
}
var file_api_ownhub_v1_tool_proto_depIdxs = []int32{
	10, // 0: ownhub.v1.AIChatReq.history:type_name -> ownhub.v1.ChatMessage
	0,  // 1: ownhub.v1.ToolService.Ping:input_type -> ownhub.v1.PingReq
	2,  // 2: ownhub.v1.ToolService.GetTimestamp:input_type -> ownhub.v1.GetTimestampReq
	4,  // 3: ownhub.v1.ToolService.GenerateToken:input_type -> ownhub.v1.GenerateTokenReq
	6,  // 4: ownhub.v1.ToolService.DigestText:input_type -> ownhub.v1.DigestTextReq
	8,  // 5: ownhub.v1.ToolService.AIChat:input_type -> ownhub.v1.AIChatReq
	11, // 6: ownhub.v1.ToolService.AIProcessText:input_type -> ownhub.v1.AIProcessTextReq
	1,  // 7: ownhub.v1.ToolService.Ping:output_type -> ownhub.v1.PingReply
	3,  // 8: ownhub.v1.ToolService.GetTimestamp:output_type -> ownhub.v1.GetTimestampReply
	5,  // 9: ownhub.v1.ToolService.GenerateToken:output_type -> ownhub.v1.GenerateTokenReply
	7,  // 10: ownhub.v1.ToolService.DigestText:output_type -> ownhub.v1.DigestTextReply
	9,  // 11: ownhub.v1.ToolService.AIChat:output_type -> ownhub.v1.AIChatReply
	12, // 12: ownhub.v1.ToolService.AIProcessText:output_type -> ownhub.v1.AIProcessTextReply
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_ownhub_v1_tool_proto_init() }
func file_api_ownhub_v1_tool_proto_init() {
	if File_api_ownhub_v1_tool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ownhub_v1_tool_proto_rawDesc), len(file_api_ownhub_v1_tool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ownhub_v1_tool_proto_goTypes,
		DependencyIndexes: file_api_ownhub_v1_tool_proto_depIdxs,
		MessageInfos:      file_api_ownhub_v1_tool_proto_msgTypes,
	}.Build()
	File_api_ownhub_v1_tool_proto = out.File
	file_api_ownhub_v1_tool_proto_goTypes = nil
	file_api_ownhub_v1_tool_proto_depIdxs = nil
}
